services:
  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: demo-otel
    network_mode: host
    volumes:
      - ./dashboard.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/ascode.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    restart: 'no'
