logging.level.com.bouygtel.otel.microservices=debug
logging.level.org.springframework.boot.autoconfigure.logging=DEBUG


# Metrics
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.metrics.tags.composant=${spring.application.name}
management.metrics.tags.version=1.0-SNAPSHOT
management.metrics.tags.deployment.environment.name=PosteDeDev
management.metrics.tags.hostname=${USERNAME}
management.metrics.distribution.percentiles-histogram.http=true

management.opentelemetry.resource-attributes.composant=${spring.application.name}
management.opentelemetry.resource-attributes.version=1.0-SNAPSHOT
management.opentelemetry.resource-attributes.deployment.environment.name=PosteDeDev
management.opentelemetry.resource-attributes.hostname=${USERNAME}

# Logging
management.opentelemetry.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.transport=http
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

# Tracing
management.opentelemetry.tracing.export.include-unsampled=true
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.tracing.export.otlp.enabled=true
management.observations.enable.http=true